### ISSUE TITLE
#1

### ISSUE THREAD

**Issue by OHyeonsoft** [OHyeonsoft/a#3]
영화에 대한 평을 받아 워드투벡터를 사용해보라는 조언을 받았는데 어떻게 생각하시나요? @OHyeonsoft @WONJOONOH

**Comment by WONJOONOH** [comment]
워드투벡터를 사용하여 평을 분석을 하면 너무 많은 단어들로 분석하기가 더 어려워질것 같습니다.

**Comment by WONJOONOH** [comment]
별점을 받아 별점을 통해 협업필터링을 이용하는 건 어떤가요?

**Comment by WONJOONOH** [comment]
그리고 평론가들마다 평을 받기가 힘들것같습니다
