### ISSUE TITLE
#3 사용자가 평가한 영화와 평론가가 평가한 영화가 몇개 일치했을때 평론가 데이터를 사용할것인가.

### ISSUE THREAD

**Issue by OHyeonsoft** [OHyeonsoft/a#7]

**Comment by WONJOONOH** [comment]
10개중 3개가 일치한다면 유사성이 있다 판단해도 될것같습니다

**Comment by OHyeonsoft** [comment]
평균적으로 10개중 2.5개정도는 일치하는거같습니다. 기준이 높을수록 좋겠지만 너무 높으면 추천이 이루어지지않을수도 있으니 10개중에 3개 또는 4개중에 1개로 하면될거같습니다.
